Основное задание
MihailSergeenkov/is pull request #2
Opened 2018-11-15 19:41 UTC by MihailSergeenkov

2018-11-16 07:16 UTC, index01d requested changes

2018-11-16 07:16 UTC, index01d commented on src/Catalog.js
> +      <basketContext.Consumer>
Consumer нужно унести в BasketButton, не похоже чтобы каталог им пользовался

2018-11-16 07:25 UTC, MihailSergeenkov commented on src/Catalog.js
> +      <basketContext.Consumer>
В общем, функционально все работало, т.е. счетчик обновлялся по нажатию кнопки добавления продукта.
Но замечание принял, поправлю и сдам вместе с дополнительным заданием.

2018-11-19 07:51 UTC, index01d approved these changes

2018-11-19 07:51 UTC, index01d commented on src/ProductCard.js
> +    this.state = { productNumber: 1 };
стлистически: получилось номер продукта, а должно быть количество (quantity)

2018-11-21 17:51 UTC, merged