Задание №7
MihailSergeenkov/is pull request #6
Opened 2018-12-16 14:38 UTC by MihailSergeenkov

2018-12-16 20:29 UTC, index01d requested changes

2018-12-16 20:29 UTC, index01d commented on src/middleware/API.js
> +        const item = product.fields;
очень опасно общий middleware наделять специфичным кодом. это все ж таки дб в reducer'e

2018-12-16 20:29 UTC, index01d commented on src/middleware/API.js
> +          response: action[API_CALL].id ? result[0] : result,
аналогично здесь middleware слишком много знает о структуре

2018-12-16 20:29 UTC, index01d commented on src/containers/BasketContainer.js
> +    const basket = loadState();
данные корзины должны быть в redux-состоянии; инициализация должна производиться путем диспетчеризации действия (в коде инициализации приложения, там где нам доступен store),  которое перехватит middleware и загрузит стор из LS

2018-12-17 10:03 UTC, index01d approved these changes

2018-12-17 10:03 UTC, index01d commented on src/store/index.js
> +      entries: loadState()
хитроу, хитроу :) ок

2018-12-17 10:06 UTC, MihailSergeenkov commented on src/store/index.js
> +      entries: loadState()
а почему хитроу?))

2018-12-17 10:09 UTC, index01d commented on src/store/index.js
> +      entries: loadState()
в целом пока это рабоатет синхронно всё ок, в асинхронном кейсе все ж таки пришлось бы задиспетчерить у готового store'a действие и отработать его линейкой middleware (где уже и делался бы loadState) -> reducer

2018-12-17 10:10 UTC, index01d commented on src/store/index.js
> +      entries: loadState()
ну и чуть дальше в SSR у тебя этот вариант не проканает, тк у серверного store'a не будет знания о клиентском LS

2018-12-17 11:29 UTC, MihailSergeenkov commented on src/store/index.js
> +      entries: loadState()
хм, все-таки не совсем понял, что нужно сделать, но попробую исправить

2018-12-19 17:56 UTC, merged